package commands

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/eugenetriguba/bolt/internal/configloader"
	"github.com/eugenetriguba/bolt/internal/models"
	"github.com/eugenetriguba/bolt/internal/repositories"
	"github.com/eugenetriguba/bolt/internal/storage"
	"github.com/eugenetriguba/bolt/internal/util"
	"github.com/google/subcommands"
)

type CreateCmd struct {
	message string
}

func (*CreateCmd) Name() string { return "create" }
func (*CreateCmd) Synopsis() string {
	return "Create a new database migration."
}
func (*CreateCmd) Usage() string {
	return `create [-message]:
	Create a new database migration.
  `
}

func (cmd *CreateCmd) SetFlags(f *flag.FlagSet) {
	f.StringVar(
		&cmd.message,
		"message",
		"autogenerated",
		"Message to use for the migration",
	)
}

func (cmd *CreateCmd) Execute(
	_ context.Context,
	f *flag.FlagSet,
	_ ...interface{},
) subcommands.ExitStatus {
	cfg, err := configloader.NewConfig()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	db, err := storage.DBConnect(
		cfg.Connection.Driver,
		storage.DBConnectionString(&cfg.Connection),
	)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}
	defer db.Close()

	migrationRepo, err := repositories.NewMigrationRepo(db, cfg)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	migration := models.NewMigration(&util.RealClock{}, cmd.message)
	err = migrationRepo.Create(migration)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	return subcommands.ExitSuccess
}
