package commands

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/eugenetriguba/bolt/internal/config"
	"github.com/eugenetriguba/bolt/internal/db"
	"github.com/eugenetriguba/bolt/internal/models"
	"github.com/eugenetriguba/bolt/internal/repositories"
	"github.com/google/subcommands"
)

type CreateCmd struct {
	message string
}

func (*CreateCmd) Name() string { return "create" }
func (*CreateCmd) Synopsis() string {
	return "Create a new database migration."
}
func (*CreateCmd) Usage() string {
	return `create [-message]:
	Create a new database migration.
  `
}

func (c *CreateCmd) SetFlags(f *flag.FlagSet) {
	f.StringVar(
		&c.message,
		"message",
		"autogenerated",
		"Message to use for the migration",
	)
}

func (m *CreateCmd) Execute(
	_ context.Context,
	f *flag.FlagSet,
	_ ...interface{},
) subcommands.ExitStatus {
	conn, err := db.Connect()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	c, err := config.NewConfig()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	migrationRepo, err := repositories.NewMigrationRepo(conn, c)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	migration := models.NewMigration(m.message)
	err = migrationRepo.Create(migration)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return subcommands.ExitFailure
	}

	return subcommands.ExitSuccess
}
